//
//  PreferencesKeys.h
//  ConstructiveEditor
//
//  Copyright (c) 2012 Openminded. All rights reserved.
//

#ifndef ConstructiveEditor_PreferencesKeys_h
#define ConstructiveEditor_PreferencesKeys_h

extern NSString* const preferredAskAboutImplicitPartsDeletion;
  extern BOOL const preferredAskAboutImplicitPartsDeletion_Default;
extern NSString* const preferredPicturesSource;
  extern NSString* const preferredPicturesSource_Camera;
  extern NSString* const preferredPicturesSource_PhotoLibrary;
extern NSString* const preferredActionOnReinterpretSplitAsDetached;
  extern NSString* const preferredActionOnReinterpretSplitAsDetached_AskMe;
  extern NSString* const preferredActionOnReinterpretSplitAsDetached_RemoveDetails;
  extern NSString* const preferredActionOnReinterpretSplitAsDetached_SplitBaseAssembly;
  extern NSString* const preferredActionOnReinterpretSplitAsDetached_UseDetailsAsDetachedParts;
  extern NSString* const preferredActionOnReinterpretSplitAsDetached_Default;
extern NSString* const preferredActionOnReinterpretSplitAsRotatedOrTransformed;
  extern NSString* const preferredActionOnReinterpretSplitAsRotatedOrTransformed_AskMe;
  extern NSString* const preferredActionOnReinterpretSplitAsRotatedOrTransformed_RemoveDetails;
  extern NSString* const preferredActionOnReinterpretSplitAsRotatedOrTransformed_SplitAssemblyBeforeRotationOrTransformation;
  extern NSString* const preferredActionOnReinterpretSplitAsRotatedOrTransformed_Default;
extern NSString* const preferredActionOnReinterpretDetachedAsRotatedOrTransformed;
  extern NSString* const preferredActionOnReinterpretDetachedAsRotatedOrTransformed_AskMe;
  extern NSString* const preferredActionOnReinterpretDetachedAsRotatedOrTransformed_RemoveEverything;
  extern NSString* const preferredActionOnReinterpretDetachedAsRotatedOrTransformed_DetachFromAssemblyBeforeRotationOrTransformation;
  extern NSString* const preferredActionOnReinterpretDetachedAsRotatedOrTransformed_UseBaseAssemblyAsAssemblyBeforeRotationOrTransformation;
  extern NSString* const preferredActionOnReinterpretDetachedAsRotatedOrTransformed_Default;
extern NSString* const preferredActionOnReinterpretRotatedOrTransformedAsDetached;
  extern NSString* const preferredActionOnReinterpretRotatedOrTransformedAsDetached_AskMe;
  extern NSString* const preferredActionOnReinterpretRotatedOrTransformedAsDetached_UseAssemblyBeforeRotationOrTransformationAsBase;
  extern NSString* const preferredActionOnReinterpretRotatedOrTransformedAsDetached_RotateOrTransformBaseAssembly;
  extern NSString* const preferredActionOnReinterpretRotatedOrTransformedAsDetached_RemoveRotatedOrTransformedAssembly;
  extern NSString* const preferredActionOnReinterpretRotatedOrTransformedAsDetached_Default;
extern NSString* const preferredActionOnReinterpretRotatedAsTransformedAndViceVersa;
  extern NSString* const preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_AskMe;
  extern NSString* const preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_UseRotatedOrTransformedAssemblyAsTransformedOrRotated;
  extern NSString* const preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_TransformeOrRotateRotatedOrTransformedAssembly;
  extern NSString* const preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_RemoveRotatedOrTransformedAssembly;
  extern NSString* const preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_Default;
extern NSString* const standardActionOnAssembly;
  extern NSString* const standardActionOnAssembly_SplitToDetails;
  extern NSString* const standardActionOnAssembly_DetachSmallerParts;
  extern NSString* const standardActionOnAssembly_Rotate;
  extern NSString* const standardActionOnAssembly_Transform;
  extern NSString* const standardActionOnAssembly_Default;
#endif
