//
//  PreferencesKeys.m
//  ConstructiveEditor
//
//  Copyright (c) 2012 Openminded. All rights reserved.
//

NSString* const preferredAskAboutImplicitPartsDeletion = @"preferredAskAboutImplicitPartsDeletion";
NSString* const preferredPicturesSource = @"preferredPicturesSource";
  NSString* const preferredPicturesSource_Camera = @"preferredPicturesSource_Camera";
  NSString* const preferredPicturesSource_PhotoLibrary = @"preferredPicturesSource_PhotoLibrary";
NSString* const preferredActionOnReinterpretSplitAsDetached = @"preferredActionOnReinterpretSplitAsDetached";
  NSString* const preferredActionOnReinterpretSplitAsDetached_AskMe = @"preferredActionOnReinterpretSplitAsDetached_AskMe";
  NSString* const preferredActionOnReinterpretSplitAsDetached_RemoveDetails = @"preferredActionOnReinterpretSplitAsDetached_RemoveDetails";
  NSString* const preferredActionOnReinterpretSplitAsDetached_SplitBaseAssembly = @"preferredActionOnReinterpretSplitAsDetached_SplitBaseAssembly";
  NSString* const preferredActionOnReinterpretSplitAsDetached_UseDetailsAsDetachedParts = @"preferredActionOnReinterpretSplitAsDetached_UseDetailsAsDetachedParts";
NSString* const preferredActionOnReinterpretSplitAsRotatedOrTransformed = @"preferredActionOnReinterpretSplitAsRotatedOrTransformed";
  NSString* const preferredActionOnReinterpretSplitAsRotatedOrTransformed_AskMe = @"preferredActionOnReinterpretSplitAsRotatedOrTransformed_AskMe";
  NSString* const preferredActionOnReinterpretSplitAsRotatedOrTransformed_RemoveDetails = @"preferredActionOnReinterpretSplitAsRotatedOrTransformed_RemoveDetails";
  NSString* const preferredActionOnReinterpretSplitAsRotatedOrTransformed_SplitAssemblyBeforeRotationOrTransformation = @"preferredActionOnReinterpretSplitAsRotatedOrTransformed_SplitAssemblyBeforeRotationOrTransformation";
NSString* const preferredActionOnReinterpretDetachedAsRotatedOrTransformed = @"preferredActionOnReinterpretDetachedAsRotatedOrTransformed";
  NSString* const preferredActionOnReinterpretDetachedAsRotatedOrTransformed_AskMe = @"preferredActionOnReinterpretDetachedAsRotatedOrTransformed_AskMe";
  NSString* const preferredActionOnReinterpretDetachedAsRotatedOrTransformed_RemoveEverything = @"preferredActionOnReinterpretDetachedAsRotatedOrTransformed_RemoveEverything";
  NSString* const preferredActionOnReinterpretDetachedAsRotatedOrTransformed_DetachFromAssemblyBeforeRotationOrTransformation = @"preferredActionOnReinterpretDetachedAsRotatedOrTransformed_DetachFromAssemblyBeforeRotationOrTransformation";
  NSString* const preferredActionOnReinterpretDetachedAsRotatedOrTransformed_UseBaseAssemblyAsAssemblyBeforeRotationOrTransformation = @"preferredActionOnReinterpretDetachedAsRotatedOrTransformed_UseBaseAssemblyAsAssemblyBeforeRotationOrTransformation";
NSString* const preferredActionOnReinterpretRotatedOrTransformedAsDetached = @"preferredActionOnReinterpretRotatedOrTransformedAsDetached";
  NSString* const preferredActionOnReinterpretRotatedOrTransformedAsDetached_AskMe = @"preferredActionOnReinterpretRotatedOrTransformedAsDetached_AskMe";
  NSString* const preferredActionOnReinterpretRotatedOrTransformedAsDetached_UseAssemblyBeforeRotationOrTransformationAsBase = @"preferredActionOnReinterpretRotatedOrTransformedAsDetached_UseAssemblyBeforeRotationOrTransformationAsBase";
  NSString* const preferredActionOnReinterpretRotatedOrTransformedAsDetached_RotateOrTransformBaseAssembly = @"preferredActionOnReinterpretRotatedOrTransformedAsDetached_RotateOrTransformBaseAssembly";
  NSString* const preferredActionOnReinterpretRotatedOrTransformedAsDetached_RemoveRotatedOrTransformedAssembly = @"preferredActionOnReinterpretRotatedOrTransformedAsDetached_RemoveRotatedOrTransformedAssembly";
NSString* const preferredActionOnReinterpretRotatedAsTransformedAndViceVersa = @"preferredActionOnReinterpretRotatedAsTransformedAndViceVersa";
  NSString* const preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_AskMe = @"preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_AskMe";
  NSString* const preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_UseRotatedOrTransformedAssemblyAsTransformedOrRotated = @"preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_UseRotatedOrTransformedAssemblyAsTransformedOrRotated";
  NSString* const preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_TransformeOrRotateRotatedOrTransformedAssembly = @"preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_TransformeOrRotateRotatedOrTransformedAssembly";
  NSString* const preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_RemoveRotatedOrTransformedAssembly = @"preferredActionOnReinterpretRotatedAsTransformedAndViceVersa_RemoveRotatedOrTransformedAssembly";
